// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsDi_bawycF2aSdf1zFit41sm93cp8GDQ',
    appId: '1:609699494561:web:3fa9f44a327ffd4961cee0',
    messagingSenderId: '609699494561',
    projectId: 'flutter-reddit-43777',
    authDomain: 'flutter-reddit-43777.firebaseapp.com',
    storageBucket: 'flutter-reddit-43777.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Q5EnGngsQTJcO88cWzEgK4gS5aBQQuk',
    appId: '1:609699494561:android:6f215e6e691d281f61cee0',
    messagingSenderId: '609699494561',
    projectId: 'flutter-reddit-43777',
    storageBucket: 'flutter-reddit-43777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-JP5QIi0GJfpICv2Y9KyWgshvP3HMOwc',
    appId: '1:609699494561:ios:c24c08720472f15561cee0',
    messagingSenderId: '609699494561',
    projectId: 'flutter-reddit-43777',
    storageBucket: 'flutter-reddit-43777.appspot.com',
    iosBundleId: 'com.example.flutterReddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-JP5QIi0GJfpICv2Y9KyWgshvP3HMOwc',
    appId: '1:609699494561:ios:c24c08720472f15561cee0',
    messagingSenderId: '609699494561',
    projectId: 'flutter-reddit-43777',
    storageBucket: 'flutter-reddit-43777.appspot.com',
    iosBundleId: 'com.example.flutterReddit',
  );
}
